import 'package:flutter/material.dart';
abstract class AppIcons{
  static const String _basePath='assets/icons';
  static const String google='$_basePath/google.png';
  static const String facebook='$_basePath/facebook_1.png';
  static const String menu='$_basePath/menu1.svg';
  static const String clothes='$_basePath/clothes.svg';
  static const String laptop='$_basePath/laptop.svg';
  static const String bag='$_basePath/cart_red.svg';
  static const String shoes='$_basePath/shoes.svg';
  static const String gift='$_basePath/gift.svg';
  static const String help='$_basePath/Help.svg';
  static const String action='$_basePath/!.svg';
  static const String logout='$_basePath/Logout.svg';
  static const String privacy='$_basePath/Privacy.svg';
  static const String home='$_basePath/home.svg';
  static const String wishlist='$_basePath/wishlist.svg';
  static const String bag1='$_basePath/bag.svg';
  static const String account='$_basePath/account.svg';
  static const String like='$_basePath/wishlistb.svg';
  static const String back='$_basePath/back.svg';
  static const String car='$_basePath/car.svg';
  static const String money='$_basePath/money.svg';
  static const String replace='$_basePath/replace.svg';
  static const String policy='$_basePath/policy.svg';
  static const String redHome='$_basePath/home_red.svg';
  static const String redLike='$_basePath/wishlist_red.svg';
  static const String redCart='$_basePath/cart_red.svg';
  static const String redProfile='$_basePath/account_red.svg';
  static const String wishlist1='$_basePath/wishlist1.svg';
  static const String delete='$_basePath/delete.svg';
  static const String attation='$_basePath/attation.svg';
}
